config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root :to => "homes#top"
    get "about" => "hoems#about"
    resources :items, only: [:index, :show]
    get "customers/my_page" => "customers#show"
    get "customers/info/edit" => "customers#edit"
    patch "customers/info" => "customers#update"
    get "customers/quit" => "customers#quit"
    patch "customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index,:update,:create,:destroy]
    delete "cart_items" => "cart_items#destroy_all"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new,:create,:index,:show]
    post "orders/confirm" => "orders#confirm"
    resources :ships, only: [:index, :edit, :create, :update, :destroy]
  end
  
  namespace :admin do
    get "/" => "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :ships, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
         
  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true ,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい'}
  validates :first_name_kana,presence:true ,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい'}
  validates :postal_code,presence:true ,format: { with: /\A\d{7}\z/ }
  validates :address,presence:true
  validates :phone_number,presence:true ,format: { with: /\A\d{10,11}\z/ }
  validates :email,presence:true ,uniqueness: true
  
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
  
  def address_info
  '〒' + self.postal_code + ' ' + self.address + ' ' + self.full_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:customer_notice] = "会員の編集に成功しました"
       redirect_to admin_customer_path(@customer)
    else
      render :edit
    end   
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted)
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-8 offset-md-1'>
      <h2><%= @customer.full_name + "さんの会員情報編集" %> </h2>

      <%= form_with model: @customer,url: admin_customer_path(@customer), local:true do |f| %>
      <div class="form-group row">
        <%= f.label :会員ID, class: "col-sm-4" %>
        <%= f.label @customer.id, class: "col-sm-4" %>
      </div>

      <div class="form-group row">
        <%= f.label :氏名, class: "col-sm-4" %>
        <%= f.text_field :last_name, class: "form-control col-sm-4" %>
        <%= f.text_field :first_name, class: "form-control col-sm-4" %>
      </div>

      <div class="form-group row">
        <%= f.label :フリガナ, class: "col-sm-4" %>
        <%= f.text_field :last_name_kana, class: "form-control col-sm-4" %>
        <%= f.text_field :first_name_kana, class: "form-control col-sm-4" %>
      </div>

      <div class="form-group row">
        <%= f.label :郵便番号, class: "col-sm-4" %>
        <%= f.text_field :postal_code, class: "form-control col-sm-4" %>
      </div>

      <div class="form-group row">
        <%= f.label :住所, class: "col-sm-4" %>
        <%= f.text_field :address, class: "form-control col-sm-4" %>
      </div>

      <div class="form-group row">
        <%= f.label :電話番号, class: "col-sm-4" %>
        <%= f.text_field :phone_number, class: "form-control col-sm-4" %>
      </div>

      <div class="form-group row">
        <%= f.label :メールアドレス, class: "col-sm-4" %>
        <%= f.email_field :email, class: "form-control col-sm-4" %>
      </div>

      <div class="form-group row">
         <%= f.label :会員ステータス, class: "col-sm-4" %>
        <div class="form-check">
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, true  %>
          <%= f.label :is_deleted, "退会" %>
        </div>
      </div>

      <div class="actions text-center">
        <%= f.submit "変更を保存",class: "btn btn-lg btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-12 px-0 mx-auto mt-3'>
      <h2>会員一覧</h2>
    </div>

      <table class='table table-hover shadow-lg mt-3'>
        <thead class="bg-light">
          <tr>
            <th>会員ID</th>
            <th><u>氏名</u></th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody class="border-bottom">
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><u><%= link_to customer.full_name ,admin_customer_path(customer)%></u></td>
              <td><%= customer.email %></td>

              <% if customer.is_deleted == false %>
              <td class="text-success font-weight-bold">有効</td>
              <% else %>
              <td class="text-secondary">無効</td>
              <% end %>

            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-8 offset-md-1 mt-3'>
      <h2><%= @customer.full_name + "さんの会員詳細" %> </h2>
    </div>

    <div class='col-md-8 offset-md-1 mt-3'>
      <p class="text-success"><%= flash[:customer_notice] %></p>
     <table class='table table-borderless'>
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>

          <tr>
            <th>氏名</th>
            <td><%= @customer.full_name %></td>
          </tr>

          <tr>
            <th>フリガナ</th>
            <td><%= @customer.full_name_kana %></td>
          </tr>

          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>

          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>

          <tr>
            <th>電話番号</th>
            <td><%= @customer.phone_number %></td>
          </tr>

          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>

          <tr>
            <th>会員ステータス</th>
            <% if @customer.is_deleted == false %>
            <td class="text-success font-weight-bold">有効</td>
              <% else %>
             <td class="text-secondary">無効</td>
              <% end %>
          </tr>

            <td><%= link_to '編集する',  edit_admin_customer_path(@customer), class: "btn btn-lg btn-success" %></td>
            <td><%= link_to '注文履歴一覧を見る', admin_path(customer_search: "true", customer_id: @customer.id), class: "btn btn-lg btn-primary" %></td>

        </tbody>
      </table>

    </div>
  </div>
</div>