config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root :to => "homes#top"
    get "about" => "hoems#about"
    resources :items, only: [:index, :show]
    get "customers/my_page" => "customers#show"
    get "customers/info/edit" => "customers#edit"
    patch "customers/info" => "customers#update"
    get "customers/quit" => "customers#quit"
    patch "customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index,:update,:create,:destroy]
    delete "cart_items" => "cart_items#destroy_all"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new,:create,:index,:show]
    post "orders/confirm" => "orders#confirm"
    resources :ships, only: [:index, :edit, :create, :update, :destroy]
  end
  
  namespace :admin do
    get "/" => "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  
  validates :customer_id, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: 'は半角数字7桁で入力して下さい'}
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true, numericality: true
  validates :total_payment, presence: true, numericality: true
  validates :payment_method, presence: true
  validates :status, presence: true
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
 
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end
  
  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @order.update(order_params)
    if @order.status == "入金確認"
       @order_items.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end
  
  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class="row my-4">
    <div class="col-md-8 offset-md-1">
      <h1>注文履歴詳細</h1>
      <h3>購入者</h3>
        <p><u><%= link_to @order.customer.full_name, admin_customer_path(@order.customer_id), class: "text-dark"%></u></p>
        <h3>注文日</h3>
        <p><%= @order.created_at.strftime('%Y/%m/%d') %></p>
        <h3>配送先</h3>
          <p><%= "〒" + @order.postal_code + " " + @order.address %><br>
          <%= @order.name %>
          </p>
      <h3>支払方法</h3>
        <p><%= @order.payment_method_i18n %></p>
        <h3>注文ステータス</h3>
          <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
            <%= f.select :status, Order.statuses.keys %>
            <%= f.submit "更新", class: "btn btn-success ml-3" %>
          <% end %>
          
        <table class="table">
        <thead style="background-color: #eee;">
          <tr>
            <th><strong>商品名</strong></th>
            <th><strong>単価（税込）</strong></th>
            <th><strong>数量</strong></th>
            <th><strong>小計</strong></th>
            <th><strong>製作ステータス</strong></th>
          </tr>
        </thead>
        <tbody>
          <% @order_items.each do |order_item| %>
            <tr>
              <td><%= order_item.item.name %></td>
              <td><%= order_item.price.to_s(:delimited) %></td>
              <td><%= order_item.amount %></td>
              <td><%= order_item.subtotal.to_s(:delimited) %></td>
              <td>
                <%= form_with model: order_item, url: admin_order_item_path(order_item), method: :patch do |f| %>
                  <%= f.select :making_status, OrderItem.making_statuses.keys %>
                  <%= f.submit "更新", class: "btn btn-success ml-3" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3 d-flex align-items-end">
      <table class="table table-borderless">
        <tr>
          <td><strong>商品合計</strong></td>
          <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %></td>
        </tr>
        <tr>
          <td><strong>送料</strong></td>
          <td><%= @order.shipping_cost.to_s(:delimited) %></td>
        </tr>
        <tr>
          <td><strong>請求金額合計</strong></td>
          <td><strong><%= @order.total_payment.to_s(:delimited) %></strong></td>
        </tr>
      </table>
          
    </div>
  </div>
</div>