config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root :to => "homes#top"
    get "about" => "hoems#about"
    resources :items, only: [:index, :show]
    get "customers/my_page" => "customers#show"
    get "customers/info/edit" => "customers#edit"
    patch "customers/info" => "customers#update"
    get "customers/quit" => "customers#quit"
    patch "customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index,:update,:create,:destroy]
    delete "cart_items" => "cart_items#destroy_all"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new,:create,:index,:show]
    post "orders/confirm" => "orders#confirm"
    resources :ships, only: [:index, :edit, :create, :update, :destroy]
  end
  
  namespace :admin do
    get "/" => "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.price_add_tax * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :ships, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
         
  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true ,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい'}
  validates :first_name_kana,presence:true ,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい'}
  validates :postal_code,presence:true ,format: { with: /\A\d{7}\z/ }
  validates :address,presence:true
  validates :phone_number,presence:true ,format: { with: /\A\d{10,11}\z/ }
  validates :email,presence:true ,uniqueness: true
  
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
  
  def address_info
  '〒' + self.postal_code + ' ' + self.address + ' ' + self.full_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
  def get_image
    (image.attached?) ? image : 'star-on.png'
  end
  
  def price_add_tax
     (self.price * 1.10).round
  end
  
  def self.search(keyword)
  where("name like?", "%#{keyword}%")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  
  validates :customer_id, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: 'は半角数字7桁で入力して下さい'}
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true, numericality: true
  validates :total_payment, presence: true, numericality: true
  validates :payment_method, presence: true
  validates :status, presence: true
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

  
  def subtotal
    item.price_add_tax * amount
  end
  
end

app/models/ship.rb
class Ship < ApplicationRecord
  belongs_to :customer
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index 
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
       redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end
  
  def edit 
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
      @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    if params[:keyword]
       @keyword = Item.search(params[:keyword])
       @items = @keyword.all
    else  
       @items = Item.all
    end
  end

  def new
    @itemnew = Item.new

  end

  def create
    @itemnew = Item.new(item_params)
    if @itemnew.save
       redirect_to admin_item_path(@itemnew)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       redirect_to admin_item_path(@item)
    else
       render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<div style="padding-top: 70px;">
  <footer class="fixed-bottom border-top bg-white">
  <div class="container">
    <div class="row py-3">
      <h5 class="mx-auto">ながのCAKE</h5>
    </div>
  </div>
</footer>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <ul class="navbar-nav ml-auto">
    <% if customer_signed_in? %>
      <p class="mx-3">ようこそ、<%= current_customer.last_name %>さん！</p>
      <li>
        <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= form_with url: items_path, method: :get do |f| %>
          <%= f.text_field :keyword, placeholder: "Search" %>
          <%= f.submit "検索" %>
        <% end %>
      </li>
    <% elsif admin_signed_in?%>
      <li>
        <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "注文履歴一覧", admin_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= form_with url: admin_items_path, method: :get do |f| %>
          <%= f.text_field :keyword, placeholder: "Search" %>
          <%= f.submit "検索" %>
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to "About", about_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary mx-3" %>
      </li>
      <li>
        <%= form_with url: items_path, method: :get do |f| %>
          <%= f.text_field :keyword, placeholder: "Search" %>
          <%= f.submit "検索" %>
        <% end %>
      </li>
    <% end %>
  </ul>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= flash[:error] %>
    <%= flash[:notice] %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>